
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.backend.env.MYSQL_HOST }}
            - name: MYSQL_USER
              value: {{ .Values.backend.env.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.backend.env.MYSQL_PASSWORD }}
            - name: MYSQL_DATABASE
              value: {{ .Values.backend.env.MYSQL_DATABASE }}
