apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "relname" . }}-backend
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/acme-dns01-provider: cloudflare
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.backend.hostname | quote }}
    secretName: {{ template "relname" . }}-backend-tls
  rules:
  - host: {{ .Values.backend.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "relname" . }}-backend
            port:
              number: 80

