apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35.0-uclibc
          command: ['sh', '-c', 'until nc -z my-mysql.feb4.svc.cluster.local 3306; do echo "Waiting for MySQL..."; sleep 5; done;']
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: MYSQL_HOST
              value: my-mysql.feb4.svc.cluster.local
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: "ASDqwe123!@#"
            - name: MYSQL_DATABASE
              value: {{ .Values.backend.env.MYSQL_DATABASE }}
