apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "relname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "relname" . }}
    app.kubernetes.io/instance: {{ template "relname" . }}-backend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ template "relname" . }}
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "relname" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ template "relname" . }}
        component: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35.0-uclibc
          command: ['sh', '-c', 'until nc -z my-mysql.{{ .Values.namespace }}.svc.cluster.local 3306; do echo "Waiting for MySQL..."; sleep 5; done;']
      containers:
        - name: {{ template "relname" . }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.backend.service.port }}
            name: http-backend
          env:
            - name: MYSQL_HOST
              value: my-mysql.{{ .Values.namespace }}.svc.cluster.local
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: "ASDqwe123!@#"
            - name: MYSQL_DATABASE
              value: {{ .Values.backend.env.MYSQL_DATABASE }}
