apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "relname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "relname" . }}
    app.kubernetes.io/instance: {{ template "relname" . }}-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: {{ template "relname" . }}
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "relname" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ template "relname" . }}
        component: frontend
    spec:
      containers:
      - name: {{ template "relname" . }}-frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
          name: http-frontend
